test1:
	gcc -Wall -Werror -Wextra -Wvla -lm -g Node.c Utils.h Hash.h Test01.c -o test1
	valgrind --leak-check=full test1
	rm test1

test2:
	gcc -Wall -Werror -Wextra -Wvla -lm -g Node.c Utils.h Hash.h Test02.c -o test2
	valgrind --leak-check=full test2
	rm test2

test3:
	gcc -Wall -Werror -Wextra -Wvla -lm -g Node.c Utils.h Hash.h Test03.c -o test3
	valgrind --leak-check=full test3
	rm test3

test4:
	gcc -Wall -Werror -Wextra -Wvla -lm -g Node.c Utils.h Hash.h Test04.c -o test4
	valgrind --leak-check=full test4
	rm test4

test5:
	gcc -Wall -Werror -Wextra -Wvla -lm -g Node.c Utils.h Hash.h Test05.c -o test5
	valgrind --leak-check=full test5
	rm test5

test6:
	gcc -Wall -Werror -Wextra -Wvla -lm -g Node.c Utils.h Hash.h Test06.c -o test6
	valgrind --leak-check=full test6
	rm test6

test7:
	gcc -Wall -Werror -Wextra -Wvla -lm -g Node.c Utils.h Hash.h Test07.c -o test7
	valgrind --leak-check=full test7
	rm test7

test8:
	gcc -Wall -Werror -Wextra -Wvla -lm -g Node.c Utils.h Hash.h  Test08.c -o test8
	valgrind --leak-check=full test8
	rm test8

test9:
	gcc -Wall -Werror -Wextra -Wvla -lm -g Node.c Utils.h Hash.h Test09.c -o test9
	valgrind --leak-check=full test9
	rm test9

test10:
	gcc -Wall -Werror -Wextra -Wvla -lm -g Node.c Utils.h Hash.h Test10.c -o test10
	valgrind --leak-check=full test10
	rm test10

test11:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Hash.h Test11.c -o test11
	valgrind --leak-check=full test11
	rm test11

test12:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Hash.h Test12.c -o test12
	valgrind --leak-check=full test12
	rm test12

test13:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Hash.h Test13.c -o test13
	valgrind --leak-check=full test13
	rm test13

test14:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Hash.h Test14.c -o test14
	valgrind --leak-check=full test14
	rm test14

test15:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Hash.h Test15.c -o test15
	valgrind --leak-check=full test15
	rm test15

test16:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Hash.h Test16.c -o test16
	valgrind --leak-check=full test16
	rm test16

test17:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Hash.h Test17.c -o test17
	valgrind --leak-check=full test17
	rm test17

test18:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Hash.h Test18.c -o test18
	valgrind --leak-check=full test18
	rm test18

test19:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Hash.h Test19.c -o test19
	valgrind --leak-check=full test19
	rm test19

test20:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Hash.h Test20.c -o test20
	valgrind --leak-check=full test20
	rm test20

test21:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Hash.h Test21.c -o test21
	valgrind --leak-check=full test21
	rm test21

test22:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Hash.h Test22.c -o test22
	valgrind --leak-check=full test22
	rm test22

test23:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Hash.h Test23.c -o test23
	valgrind --leak-check=full test23
	rm test23

test24:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Hash.h Test24.c -o test24
	valgrind --leak-check=full test24
	rm test24

test25:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Hash.h Test25.c -o test25
	valgrind --leak-check=full test25
	rm test25

test26:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Hash.h Test26.c -o test26
	valgrind --leak-check=full test26
	rm test26

test27:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Hash.h Test27.c -o test27
	valgrind --leak-check=full test27
	rm test27

test28:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Hash.h Test28.c -o test28
	valgrind --leak-check=full test28
	rm test28

test29:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Hash.h Test29.c -o test29
	valgrind --leak-check=full test29
	rm test29

test30:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Hash.h Test30.c -o test30
	valgrind --leak-check=full test30
	rm test30
test31:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Hash.h Test31.c -o test31
	valgrind --leak-check=full test31
	rm test31

test32:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Hash.h Test32.c -o test32
	valgrind --leak-check=full test32
	rm test32

test33:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Hash.h Test33.c -o test33
	valgrind --leak-check=full test33
	rm test33

test34:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Hash.h Test34.c -o test34
	valgrind --leak-check=full test34
	rm test34

test35:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Hash.h Test35.c -o test35
	valgrind --leak-check=full test35
	rm test35

test36:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Hash.h Test36.c -o test36
	valgrind --leak-check=full test36
	rm test36

test37:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Hash.h Test37.c -o test37
	valgrind --leak-check=full test37
	rm test37

test38:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Hash.h Test38.c -o test38
	valgrind --leak-check=full test38
	rm test38

test39:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Hash.h Test39.c -o test39
	valgrind --leak-check=full test39
	rm test39

test40:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Hash.h Test40.c -o test40
	valgrind --leak-check=full test40
	rm test40

test41:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Test41.c -o test41
	valgrind --leak-check=full test41
	rm test41

test42:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Test42.c -o test42
	valgrind --leak-check=full test42
	rm test42

test43:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Test43.c -o test43
	valgrind --leak-check=full test43
	rm test43

test44:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Test44.c -o test44
	valgrind --leak-check=full test44
	rm test44

test45:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Test45.c -o test45
	valgrind --leak-check=full test45
	rm test45

test46:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Test46.c -o test46
	valgrind --leak-check=full test46
	rm test46

test47:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Test47.c -o test47
	valgrind --leak-check=full test47
	rm test47

test48:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Test48.c -o test48
	valgrind --leak-check=full test48
	rm test48

test49:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Test49.c -o test49
	valgrind --leak-check=full test49
	rm test49

test50:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Test50.c -o test50
	valgrind --leak-check=full test50
	rm test50
presub:
	gcc -Wall -Werror -Wextra -Wvla -lm -g HashSet.c Utils.h Hash.h Presub.c -o presub
	valgrind --leak-check=full presub
	rm presub

clear:
	rm test*